[package]
name = "oktopass"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
rand = "0.9.1"
rand-extra = "0.1.0"
serde = { version =  "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
